# Generated by Django 4.0.4 on 2022-05-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, default='No Photo', help_text='Please add alternative text', max_length=255, null=True, verbose_name='Alternative text'),
        ),
    ]
